### ISSUE TITLE
Introduce offset for walking time to station

### ISSUE THREAD

**Issue by gunrunner20** [jalibu/MMM-RNV#1]
**Is your feature request related to a problem? Please describe.**
In the current setup, connections are shown which can't be reached any more in time (when leaving home in that particular moment and walking to the station).

**Describe the solution you'd like**
Introduction of a config parameter (e.g. _walkingTimeOffsetMinutes_ which defaults to 0) to hide connections which are earlier than now()+walkingTimeOffsetMinutes.

**Comment by jalibu** [comment]
Bitte mal Version 1.1.0 testen
