### ISSUE TITLE
Can´t see anything in MagicMirror

### ISSUE THREAD

**Issue by kusselin** [jalibu/MMM-RNV#3]
Hallo Jan, ich wollte dein Modul für Magic Mirror nutzen...habe es über console in den module ordner installiert wie beschrieben mit npm install....danach habe ich in der Magicmirror config datei folgendes eingetragen:

{
     module: "MMM-RNV",
     position: "top_left",
     config: {
         animationSpeedMs: 2 * 1000, // 2 seconds
         credentials: {
            clientId: "",
            clientSecret: "",
            resourceId: "",
            tenantId: "",
         },
         excludeLines: [5], // example ["N1", "5"]
         excludePlatforms: [], // example ["A"]
         highlightLines: [], // example ["1"]
         maxResults: 10,
         showLineColors: true,
         showPlatform: false,
         showTableHeadersAsSymbols: false,
         stationId: '1585',
         timeformat: 'HH:mm',
         updateIntervalMs: 1 * 60 * 1000, // every 1 minute
         walkingTimeMs: 3 * 60 * 1000 // 3 minutes footwalk
     }
 },
API direkt hat mir die RNV nicht zugesendet...nur die ID´s!!

nach einem Start des MM kommt aber nur Lade......

Was mache ich falsch?
Über ne kurze Rückinfo herzlichen Dank

Gruss
Kussel

muss ich da den GraphQL API eintragen oder den gtfs-rt Endpoint??

**Comment by jalibu** [comment]
Was genau meinst du mit "API hat dir die RNV nicht zugesendet"?

Ohne ClientId, ClientSecret, resourceId und tenantId wird es nicht funktionieren

**Comment by kusselin** [comment]
Halt hab mich falsch ausgedrückt..ich habe die ID bekommen ..passt schon..
