### ISSUE TITLE
MMM-RNV

### ISSUE THREAD

**Issue by HeisemerBub** [jalibu/MMM-RNV#4]
Hallo Jan,

hat sich an dem Module was geändert...ich habe von der RNV neue IDs gesendet bekommen udn trotzdem funzt das Modul nicht mehr...

Wäre nett wenn du dich mal melden könntest.

Gruss 
Heisemer

Hier meine Config:
{
		  module: 'MMM-RNV',
		  header: 'RNV Abfahrstmonitor',
		  position: 'bottom_center',
		  config: {
			updateInterval: "60000",
			animationSpeed: "2000",
			stationID: "1585", // HD-Bahnhof
			numJourneys: "5",
			clientID: 'c86xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc8',
			tenantID: '87cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx616c9',
			clientSecret: 'zx_8Q~Uxxxxxxxxxxxxxxxxxxxx1',
			resourceID: '1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxaf',
			coloredLines: "true",
			showLineIcons: "true",
			useColorForRealTimeInfo: "true",
			showTableHeader: "true",
		  }
		},

**Comment by jalibu** [comment]
@jupadin kannst du dazu was sagen? ich wohne nicht mehr im RNV Gebiet und nutze das Modul daher nicht mehr

**Comment by jalibu** [comment]
@HeisemerBub auffällig an deiner Config ist die falsche verwendung von Numbers und Booleans im JSON Objekt. Diese dürfen nicht in Quotes stehen

**Comment by jalibu** [comment]
@HeisemerBub deine oben genannte Config ist mit "meiner" Version dieses Moduls auch nicht kompatibel (siehe Readme). Sie stammt vermutlich von Julians Implementierung.

**Comment by HeisemerBub** [comment]
> @HeisemerBub deine oben genannte Config ist mit "meiner" Version dieses Moduls auch nicht kompatibel (siehe Readme). Sie stammt vermutlich von Julians Implementierung.

Das war der entscheidende Hinweis...ich habe die Config von Dir aber das Modul von Julian installiert...Modul noch mal gelöscht und richtiges installiert...jetzt gehts...danke Euch
